sudo: false
language: python
services:
- "docker"
env:
  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.3
    - PYTHON_VERSION: 3.4
    - PYTHON_VERSION: 3.5
    - PYTHON_VERSION: 3.6
script:
  - sed -i -e "s/2.7/${PYTHON_VERSION}/" Dockerfile
  - docker build --rm -t infrastructureascode/uwsgi .
  - docker images
